#!/bin/sh
if [ "${SKIP_HOOKS:-0}" -gt 0 ] 2>/dev/null; then
    echo "[POST-CHECKOUT] skipping hooks ($SKIP_HOOKS)"
    exit 0
fi

# ### run npm install ###
echo "[POST-CHECKOUT] 📦 Checking for changes to dependencies"
# $1 is the new HEAD pointer
NEWHEAD=$1
# $2 is the previous HEAD pointer
OLDHEAD=$2
# extract all paths to package-lock.json files
PACKAGES=$(git diff --name-only "$OLDHEAD" "$NEWHEAD" | grep -E "^package-lock\.json" || true)

if [ -n "$PACKAGES" ]; then
    for package in $PACKAGES; do
        echo "📦 $package was changed."
    done
    echo "📦 Running npm install to update your dependencies..."
    npm install --no-workspaces
    npm run lint:fix
else
    echo "📦 All packages up-to-date. No need to run npm install."
fi
